version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"