jwt:
  key:
    public: classpath:app.pub
    private: classpath:app.key
    id: bootiful
  persistence:
    password: password
    salt: 626F6F746966756C
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
